version: '3.2'

# This docker compose file will launch all the services locally
services:
  # The Flask API
  ecs_base_app:
    build: .
    image: "$DOCKER_IMAGE:$DOCKER_TAG"
    ports:
      - $LOCAL_PORT:80
    restart: always
    volumes:
      # mount at runtime to prevent rebuilds for config changes
      - type: bind
        source: .env
        target: /app/.env
        read_only: true
      - type: bind
        source: ./scripts/
        target: /app/scripts/
        read_only: true
